# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-1
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - run: aws s3 sync dist/ s3://thecodeboss --delete
      - run: aws cloudfront create-invalidation --distribution-id EAPXF0HO4B4M5 --paths "/*"
